// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
	site: 'https://docs.healthlog.dev',
	redirects: {
		// Pre-Diátaxis tree retired into the canonical sections — keep old URLs alive.
		'/integrations/withings/': '/guides/connect-withings/',
		'/integrations/whoop/': '/guides/connect-whoop/',
		'/integrations/oura/': '/guides/connect-oura/',
		'/integrations/polar/': '/guides/connect-polar/',
		'/integrations/nightscout/': '/guides/connect-nightscout/',
		'/integrations/apple-health/': '/guides/import-apple-health/',
		'/integrations/fitbit/': '/guides/connect-google-health/',
		'/integrations/google-health-fitbit/': '/guides/connect-google-health/',
		'/integrations/ai-providers/': '/guides/ai-providers/',
		'/concepts/source-priority/': '/explanation/source-priority/',
		'/concepts/derived-metrics/': '/explanation/health-scores/',
		'/methodology/overview/': '/explanation/health-scores/',
		'/methodology/health-score/': '/explanation/health-scores/',
		'/methodology/medication-compliance/': '/explanation/medication-compliance/',
		'/api/native-clients/': '/reference/native-clients/',
		'/api/sync/': '/reference/sync/',
		'/admin/backups/': '/guides/backups/',
		'/settings/ai-providers/': '/guides/ai-providers/',
	},
	integrations: [
		starlight({
			title: 'HealthLog',
			description: 'Self-hosted health tracking PWA — documentation',
			defaultLocale: 'root',
			locales: {
				root: { label: 'English', lang: 'en' },
			},
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/MBombeck/HealthLog' },
			],
			editLink: {
				baseUrl: 'https://github.com/MBombeck/healthlog-docs/edit/main/',
			},
			lastUpdated: true,
			customCss: ['./src/styles/custom.css'],
			expressiveCode: {
				themes: ['dracula', 'github-light'],
				styleOverrides: {
					borderRadius: '0.5rem',
				},
			},
			sidebar: [
				{
					label: 'Getting Started',
					items: [
						{ slug: 'getting-started/introduction' },
						{ slug: 'getting-started/self-host-in-10-minutes' },
						{ slug: 'getting-started/first-steps' },
						{ slug: 'getting-started/connect-ios-app' },
						{ slug: 'ios/ios-app', label: 'The iOS app' },
					],
				},
				{
					label: 'How-to Guides',
					items: [
						{ slug: 'guides', label: 'Overview' },
						{ slug: 'guides/connect-withings' },
						{ slug: 'guides/connect-whoop' },
						{ slug: 'guides/connect-oura' },
						{ slug: 'guides/connect-polar' },
						{ slug: 'guides/connect-strava' },
						{ slug: 'guides/connect-google-health' },
						{ slug: 'guides/connect-fitbit' },
						{ slug: 'guides/connect-nightscout' },
						{ slug: 'guides/import-apple-health' },
						{ slug: 'guides/source-priority' },
						{ slug: 'guides/track-medications' },
						{ slug: 'guides/nutrients' },
						{ slug: 'guides/clinical-signals' },
						{ slug: 'guides/structured-records' },
						{ slug: 'guides/reminder-channels' },
						{ slug: 'guides/ai-providers' },
						{ slug: 'guides/coach-plans' },
						{ slug: 'guides/document-vault' },
						{ slug: 'guides/shared-access' },
						{ slug: 'guides/managed-profiles' },
						{ slug: 'guides/mcp-server' },
						{ slug: 'guides/invites' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ slug: 'reference', label: 'Overview' },
						{ slug: 'reference/api-overview' },
						{ slug: 'reference/api-endpoints' },
						{ slug: 'reference/native-clients' },
						{ slug: 'reference/sync' },
						{ slug: 'reference/mcp' },
						{ slug: 'reference/environment-variables' },
						{ slug: 'reference/data-model' },
						{ slug: 'reference/fhir-api' },
						{ slug: 'reference/webhooks' },
					],
				},
				{
					label: 'Explanation',
					items: [
						{ slug: 'explanation', label: 'Overview' },
						{ slug: 'explanation/non-diagnostic-standard' },
						{ slug: 'explanation/medication-compliance' },
						{ slug: 'explanation/health-scores' },
						{ slug: 'explanation/source-priority' },
						{ slug: 'explanation/proactive-coach' },
						{ slug: 'explanation/environmental-module' },
						{ slug: 'explanation/blood-pressure-targets' },
						{ slug: 'explanation/encryption-at-rest' },
						{ slug: 'explanation/privacy-architecture' },
						{ slug: 'explanation/record-sharing' },
						{ slug: 'explanation/mcp-security' },
						{ slug: 'explanation/timezone-model' },
					],
				},
				{
					label: 'Methodology',
					items: [
						{ slug: 'methodology/recovery' },
						{ slug: 'methodology/chronotype' },
						{ slug: 'methodology/glucose-clinical' },
						{ slug: 'methodology/glycemic-risk' },
					],
				},
				{
					label: 'Health Knowledge',
					items: [
						{ slug: 'knowledge' },
						{ slug: 'knowledge/blood-pressure' },
						{ slug: 'knowledge/resting-heart-rate' },
						{ slug: 'knowledge/hrv' },
						{ slug: 'knowledge/glucose-hba1c' },
						{ slug: 'knowledge/longevity-labs' },
						{ slug: 'knowledge/weight-bmi' },
						{ slug: 'knowledge/waist-circumference' },
						{ slug: 'knowledge/body-composition' },
						{ slug: 'knowledge/grip-strength' },
						{ slug: 'knowledge/sleep' },
						{ slug: 'knowledge/spo2' },
						{ slug: 'knowledge/respiratory-rate' },
						{ slug: 'knowledge/temperature' },
						{ slug: 'knowledge/vo2max-activity' },
						{ slug: 'knowledge/menstrual-cycle' },
						{ slug: 'knowledge/mood' },
						{ slug: 'knowledge/pain' },
						{ slug: 'knowledge/environment' },
					],
				},
				{
					label: 'Features',
					items: [
						{ slug: 'features', label: 'Feature catalogue' },
						{ slug: 'features/dashboard-customization' },
						{ slug: 'dashboard/comparison' },
						{ slug: 'features/achievements-hidden' },
						{ slug: 'features/fhir-export' },
						{ slug: 'insights/how-it-works' },
						{ slug: 'insights/today' },
						{ slug: 'insights/intraday-pulse' },
						{ slug: 'insights/metric-catalog' },
						{ slug: 'insights/ecg-recordings' },
					],
				},
				{
					label: 'Self-hosting & Operations',
					items: [
						{ slug: 'self-hosting/coolify' },
						{ slug: 'self-hosting/tls-certificates' },
						{ slug: 'security/certificate-pinning' },
						{ slug: 'guides/reverse-proxy' },
						{ slug: 'guides/backups' },
						{ slug: 'guides/encryption-key-rotation' },
						{ slug: 'guides/updates-and-deploy' },
						{ slug: 'self-hosting/scaling' },
						{ slug: 'self-hosting/troubleshooting' },
					],
				},
				{
					label: 'Security & Privacy',
					items: [
						{ slug: 'security/overview', label: 'Security and privacy' },
						{ slug: 'self-hosting/gdpr' },
					],
				},
				{
					label: 'Project',
					items: [
						{ slug: 'support', label: 'Support and contact' },
						{ slug: 'account/data-deletion' },
						{ slug: 'license' },
					],
				},
			],
		}),
	],
});
